"""added fullname to Order

Revision ID: 1e36d56138ce
Revises: a45ebdf19ab0
Create Date: 2023-10-31 03:18:15.972741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e36d56138ce'
down_revision = 'a45ebdf19ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
