"""removed vendor_id

Revision ID: 45e87e76d5e6
Revises: f1f52c73a640
Create Date: 2023-11-05 12:49:46.372418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e87e76d5e6'
down_revision = 'f1f52c73a640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
