"""add latitude, longitude to vendor

Revision ID: 4ff4bcaf5aeb
Revises: e5af6c4e968c
Create Date: 2023-10-28 09:28:48.556123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff4bcaf5aeb'
down_revision = 'e5af6c4e968c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.String(), nullable=True))
        batch_op.drop_column('map_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###
