"""added isAdmin column to users

Revision ID: 7729e396a7ba
Revises: 14d785a4135f
Create Date: 2023-10-29 01:41:01.318371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7729e396a7ba'
down_revision = '14d785a4135f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###
