"""removed columns from orders, added payments table and relationship to order

Revision ID: 950c36d02732
Revises: f29c69d3a0e5
Create Date: 2023-10-29 22:36:17.391954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950c36d02732'
down_revision = 'f29c69d3a0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_uid', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_payment_uid_payments'), 'payments', ['payment_uid'], ['payment_uid'])
        batch_op.drop_column('order_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_uid', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_orders_payment_uid_payments'), type_='foreignkey')
        batch_op.drop_column('payment_uid')

    # ### end Alembic commands ###
