"""added vendor_id to order table

Revision ID: a45ebdf19ab0
Revises: a55cddd01f54
Create Date: 2023-10-31 02:33:04.477406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45ebdf19ab0'
down_revision = 'a55cddd01f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
