"""added a bunch of columns to order table

Revision ID: a55cddd01f54
Revises: bba9d159c2e6
Create Date: 2023-10-31 02:06:00.073590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55cddd01f54'
down_revision = 'bba9d159c2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('purchased_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount')
        batch_op.drop_column('email')
        batch_op.drop_column('county')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('delivery_type')

    # ### end Alembic commands ###
