"""added MPESA columns to order table

Revision ID: d7a606719636
Revises: 7729e396a7ba
Create Date: 2023-10-29 20:36:51.708632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a606719636'
down_revision = '7729e396a7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment__date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paid_by_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('paid_by_number')
        batch_op.drop_column('payment__date')
        batch_op.drop_column('mpesa_receipt_code')

    # ### end Alembic commands ###
