"""remove cartitem id from orders table

Revision ID: dbe4555c6709
Revises: bdaed81594e5
Create Date: 2023-10-28 17:12:11.444712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe4555c6709'
down_revision = 'bdaed81594e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_product_id_products', type_='foreignkey')
        batch_op.drop_constraint('fk_orders_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_orders_product_id_products'), 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_product_id_products'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orders_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_orders_product_id_products', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
