"""changed columns and relationships in the order table

Revision ID: f1f52c73a640
Revises: 1c07c0dd8129
Create Date: 2023-11-05 12:48:56.340365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f52c73a640'
down_revision = '1c07c0dd8129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_product_id_products', type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_orders_product_id_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
