"""removed columns from orders, added payments table and relationship to order

Revision ID: f29c69d3a0e5
Revises: d7a606719636
Create Date: 2023-10-29 21:40:05.042287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29c69d3a0e5'
down_revision = 'd7a606719636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mpesa_receipt_code', sa.String(), nullable=True),
    sa.Column('payment_date', sa.String(), nullable=True),
    sa.Column('paid_by_number', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('payment_uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_uid', sa.String(), nullable=True))
        batch_op.drop_column('payment__date')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('mpesa_receipt_code')
        batch_op.drop_column('paid_by_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_code', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('payment__date', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('order_uid')

    op.drop_table('payments')
    # ### end Alembic commands ###
